### ISSUE TITLE
Is this library maintained?

### ISSUE THREAD

**Issue by ehmicky** [alexindigo/cartesian#77]
I am developing a similar library called [`fast-cartesian`](https://github.com/ehmicky/fast-cartesian) and would like to know whether this library is maintained, so I know whether to add link to it or not. Thanks!

**Comment by alexindigo** [comment]
It is maintained and used in few other projects.
Do you want to create PR to this one and make it fast? :)

Thank you.

**Comment by ehmicky** [comment]
No my library is already complete and used in other libraries. But thanks for answering!

**Comment by alexindigo** [comment]
This is cool :) https://github.com/ehmicky/fast-cartesian/blob/master/benchmarks/main.js

**Comment by ehmicky** [comment]
Thanks! That's a work in progress: [`check-speed`](https://github.com/ehmicky/check-speed).

**Comment by ehmicky** [comment]
Also if you are using cartesian products for unit testing, feel free to check my other project [`test-each`](https://github.com/ehmicky/test-each)! :)
